SourcePath : C:\Users\59010374\Desktop\test.txt
TargetPath : C:\Users\59010374\Desktop\out.txt

DB :
    enable : true
    Schema : test
    Table  : menus
    JSONPath : C:\Users\59010374\Desktop\out.json